---
  - name: HHVM | get gpg key
    apt_key: url=http://dl.hhvm.com/conf/hhvm.gpg.key state=present
    become: yes
    tags:
     - hhvm

  - name: HHVM | add deb repository
    apt_repository: repo='deb http://dl.hhvm.com/debian {{ ansible_distribution_release }} main' state=present
    tags:
     - hhvm

  - name: HHVM | install hhvm packages
    apt:
      pkg:
        - hhvm-fastcgi
      state: present
      update_cache: yes
      force: yes
    become: yes
    notify: restart hhvm
    tags:
     - hhvm

  - name: HHVM | get hhvm install path realtime
    command: which hhvm
    register: hhvm_path
    changed_when: false
    tags:
     - hhvm

  - name: HHVM | Console operations - symlink hhvm as php
    file: src="{{ hhvm_path.stdout }}" dest=/usr/bin/php state=link
    become: yes
    tags:
     - hhvm

